//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT.Middleware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Connection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_Connection()
        {
            this.t_Company = new HashSet<t_Company>();
        }
    
        public byte IdConnection { get; set; }
        public string Descripcion { get; set; }
        public string ConnectionString { get; set; }
        public string Proveedor { get; set; }
        public string FileName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_Company> t_Company { get; set; }
    }
}
