//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT.Middleware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_OrdersDetail
    {
        public long DocEntry { get; set; }
        public int LineNum { get; set; }
        public long IdCompany { get; set; }
        public string ItemCode { get; set; }
        public string Dscription { get; set; }
        public decimal Quantity { get; set; }
        public System.DateTime ShipDate { get; set; }
        public decimal Price { get; set; }
        public decimal DiscPrcnt { get; set; }
        public decimal LineTotal { get; set; }
        public string WhsCode { get; set; }
        public decimal VatSum { get; set; }
        public string TaxCode { get; set; }
    
        public virtual t_Orders t_Orders { get; set; }
    }
}
