//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT.Middleware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_PurchaseRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_PurchaseRequest()
        {
            this.t_PurchaseRequestDetail = new HashSet<t_PurchaseRequestDetail>();
        }
    
        public long DocEntry { get; set; }
        public int DocNum { get; set; }
        public Nullable<int> Branch { get; set; }
        public System.DateTime DocDate { get; set; }
        public Nullable<System.DateTime> DocDueDate { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string NumAtCard { get; set; }
        public decimal VatSum { get; set; }
        public decimal DocTotal { get; set; }
        public decimal DiscSum { get; set; }
        public string Comments { get; set; }
        public Nullable<int> SlpCode { get; set; }
        public string Requester { get; set; }
        public string ReqName { get; set; }
        public string DocStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_PurchaseRequestDetail> t_PurchaseRequestDetail { get; set; }
    }
}
