//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT.Integracion.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SALESFORCESEntities : DbContext
    {
        public SALESFORCESEntities()
            : base("name=SALESFORCESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_Company> t_Company { get; set; }
        public virtual DbSet<t_Connection> t_Connection { get; set; }
        public virtual DbSet<t_Customer> t_Customer { get; set; }
        public virtual DbSet<t_CustomerAddress> t_CustomerAddress { get; set; }
        public virtual DbSet<t_Item> t_Item { get; set; }
        public virtual DbSet<t_ItemPrice> t_ItemPrice { get; set; }
        public virtual DbSet<t_Orders> t_Orders { get; set; }
        public virtual DbSet<t_OrdersDetail> t_OrdersDetail { get; set; }
        public virtual DbSet<t_PurchaseRequest> t_PurchaseRequest { get; set; }
        public virtual DbSet<t_PurchaseRequestDetail> t_PurchaseRequestDetail { get; set; }
        public virtual DbSet<t_Seller> t_Seller { get; set; }
    }
}
