//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT.Integracion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ItemPrice
    {
        public string ItemCode { get; set; }
        public long IdCompany { get; set; }
        public int PriceList { get; set; }
        public Nullable<decimal> Price { get; set; }
        public System.DateTime FechaUp { get; set; }
    
        public virtual t_Item t_Item { get; set; }
    }
}
