//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT.Integracion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_PurchaseRequestDetail
    {
        public long DocEntry { get; set; }
        public int LineNum { get; set; }
        public string ItemCode { get; set; }
        public string Dscription { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public string ReqDate { get; set; }
        public decimal Price { get; set; }
        public decimal PriceAfVAT { get; set; }
        public decimal PriceBefDi { get; set; }
        public string WhsCode { get; set; }
        public Nullable<decimal> OpenQty { get; set; }
        public decimal VatSum { get; set; }
        public decimal DiscPrcnt { get; set; }
        public decimal LineTotal { get; set; }
    
        public virtual t_PurchaseRequest t_PurchaseRequest { get; set; }
    }
}
